# Generated by Django 4.1.2 on 2022-10-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Квартира')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(max_length=30, verbose_name='Дата выставки на продажу')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('apartment', models.ForeignKey(blank=True, db_column='apartment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.apartments', verbose_name='Квартира')),
                ('buyer_sell', models.ForeignKey(db_column='buyer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_sell', to='mysite.users', verbose_name='Владелец')),
                ('owner_sell', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_sell', to='mysite.users', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='apartments',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='mysite.apartmentsell', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='apartments',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='mysite.apartmentsell', verbose_name='Владелец'),
        ),
    ]
