# Generated by Django 4.1.2 on 2022-10-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartments',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='mysite.users', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='mysite.users', verbose_name='Владелец'),
        ),
    ]
