# Generated by Django 4.1.2 on 2022-10-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_apartmentsell_buyer_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentsell',
            name='buyer_sell',
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='mysite.users', verbose_name='Владелец'),
        ),
    ]
