# Generated by Django 4.1.2 on 2022-10-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_apartments_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='apartmentsell',
            name='apartment_id',
        ),
        migrations.RemoveField(
            model_name='apartmentsell',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='apartments',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='mysite.users', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='apartment',
            field=models.ForeignKey(blank=True, db_column='apartment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.apartments', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='buyer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='mysite.users', verbose_name='Владелец'),
        ),
    ]
