# Generated by Django 4.1.2 on 2022-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_users_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
