# Generated by Django 4.1.2 on 2022-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_users_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartments',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
